version: '3.5'
services:
  api-1:
    build: .
    container_name: API-1
    ports:
      - 9001:9001
    restart: 'always'
    environment:
      - PORT=9001
      - SERVER_NAME=API-1
      - NODE_ENV=development

  api-2:
    build: .
    container_name: API-2
    ports:
      - 9002:9002
    restart: 'always'
    environment:
      - PORT=9002
      - SERVER_NAME=API-2
      - NODE_ENV=development

  api-3:
    build: .
    container_name: API-3
    ports:
      - 9003:9003
    restart: 'always'
    environment:
      - PORT=9003
      - SERVER_NAME=API-3
      - NODE_ENV=development

  nginx:
    image: nginx
    container_name: NGINX-API
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "9000:9000"
    restart: 'always'
    depends_on:
      - API-1
      - API-2
      - API-3
